export const themeColors = [
  { name: "red", value: "#EF4444" },
  { name: "green", value: "#10B981" },
  { name: "yellow", value: "#F59E0B" },
  { name: "blue", value: "#3B82F6" },
  { name: "purple", value: "#8B5CF6" },
  { name: "pink", value: "#EC4899" },
  { name: "teal", value: "#14B8A6" },
  { name: "orange", value: "#F97316" },
   { name: "indigo", value: "#4F46E5" },
  { name: "lime", value: "#84CC16" },
  { name: "cyan", value: "#06B6D4" },
  { name: "rose", value: "#F43F5E" },
  { name: "amber", value: "#FBBF24" },
  { name: "violet", value: "#7C3AED" },
  { name: "emerald", value: "#047857" },
  { name: "sky", value: "#0e8fcbff" },
 ];
